name: Bug Report
description: Report a bug you encountered with the Okta Angular SDK
labels: [ bug ]
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug?
      description: |
        Please be as detailed as possible. This will help us address the bug in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is expected to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What is the actual behavior?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps?
      description: |
        Please provide as much detail as possible to help us reproduce your bug.
        A reproduction repo is very helpful for us as well.
    validations:
      required: true

  - type: textarea
    id: sdkVersion
    attributes:
      label: SDK Versions
      description: |
        Please provide versions of all `@okta/` scoped packages used in application,
        as well as any relevant non-Okta packages
    validations:
      required: true

  - type: textarea
    id: execEnv
    attributes:
      label: Execution Environment
      description: |
        Please describe the application's execution environment
        For example: browser(s), NodeJS, and OS versions
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?
